name = "PatternDispatch"
uuid = "8afb3109-34b0-48b6-bc93-2f1beb14c099"
authors = ["MasonProtter <mason.protter@gmail.com>"]
version = "0.1.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Rematch = "bfecab0d-fd4d-5014-a23f-56c5fae6447a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
